version: '3.9'

services:
  telegraf:
    image: telegraf:1.16
    restart: always
    ports:
    - "9273:9273"
    volumes:
    - ${PWD}/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
    - proxynet

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
    - "9090:9090"
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.path=/prometheus"] 
    volumes:
    - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - persist-prom-tsdb:/prometheus/
    networks:
    - proxynet

  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - ${PWD}/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    - ${PWD}/prometheus_ds.yml:/etc/grafana/provisioning/dashboards/prometheus_ds.yml:ro
    - ${PWD}/Network-Up-Dashboard.json:/var/lib/grafana/dashboards/Network-Up-Dashboard.json:ro
    networks:
    - proxynet

volumes:
  persist-prom-tsdb:  
networks:
  proxynet:
    name: custom_network

